# CI pipeline. Publish is done automatially in GitHub Actions

name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)-rolling

variables:
  - name: buildConfiguration
    value: Release
  - name: nugetOutputPath
    value: $(Build.StagingDirectory)/nupkgs

trigger:
  batch: true
  branches:
    include:
      - master
pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: windows-2022

jobs:
  - job: "BuildNuGets"
    displayName: "Build NuGet packages"
    workspace:
      clean: outputs
    variables:
      nugetOutputPath: "$(Build.StagingDirectory)/nupkgs"
    steps:
      - checkout: self
        clean: true

      - task: UseDotNet@2
        displayName: Check .NETCore SDK
        inputs:
          version: 3.1.x
      - task: UseDotNet@2
        displayName: "Check .NET SDK"
        inputs:
          version: 6.x

      - task: NuGetToolInstaller@1
        displayName: Check NuGet client
        inputs:
          versionSpec: 6.x
          checkLatest: true

      - task: PowerShell@2
        displayName: Generate Bindings
        inputs:
          targetType: filePath
          filePath: Generate-Bindings.ps1
          arguments: -BuildConfiguration $(buildConfiguration)

      - task: PowerShell@2
        displayName: Generate NuGet packages
        inputs:
          targetType: filePath
          filePath: Generate-NuGets.ps1
          arguments: -Version $(Build.BuildNumber) -Outputfolder $(nugetOutputPath) -BuildConfiguration $(buildConfiguration)

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: NuGets"
        inputs:
          PathtoPublish: $(nugetOutputPath)
          ArtifactName: NuGets
